services:
    api:
        image: putrawan/epc:latest #change with image register in dockerhub
        restart: always
        ports:
          - 5000:5000
    ngrok:
        image: ngrok/ngrok:latest
        restart: unless-stopped
        command:
          - "start"
          - "--all"
          - "--config"
          - "/etc/ngrok.yml"
        volumes:
          - ./ngrok.yml:/etc/ngrok.yml
        ports:
          - 4040:4040